DROP DATABASE IF EXISTS WORDLE;
CREATE DATABASE WORDLE; 
USE WORDLE;

DROP TABLE IF EXISTS WORDLIST;
CREATE TABLE WORDLIST (
	Id				int not null AUTO_INCREMENT,
	Word			char(4) not null, -- positive value denotes North and negative value denotes South
    Hint			varchar(100) not null, -- positive value denotes East and negative value denotes West
    primary key (Id)
);

INSERT INTO WORDLIST(Word, Hint) VALUES
("iron", "A type of metal"),
("card", "You can play games with this"),
("lamb", "Mary had a little ____"),
("zone", "You can be in the ____"),
("word", "This is something you are trying to guess right now"),
("jinx", "You owe me a soda"),
("butt", "Chicken ____"),
("cash", "You can buy things with this"),
("weed", "420 anyone?"),
("html", "A markup language"),
("curl", "enables data exchange between a device and a server through a terminal"),
("doge", "A cryptocurrency was named after this"),
("cube", "A 3-dimensional shape"),
("frog", "Croak"),
("lost", "You do not want to be in this situation in the woods"),
("moon", "Earth's natural satellite"),
("star", "A celestial body that emits light"),
("fire", "Produces heat and light"),
("fish", "Plenty of ____ in the sea"),
("ship", "Used for transportation on water"),
("blue", "Once in a ____ moon"),
("play", "Engage in an activity for enjoyment"),
("gold", "Precious metal"),
("park", "Outdoor recreational area"),
("lamp", "Source of light"),
("jump", "Move off the ground with both feet"),
("help", "Assist or aid"),
("baby", "Newborn human"),
("gift", "Present or token of appreciation"),
("book", "Written or printed work"),
("road", "Paved way for vehicles"),
("song", "Musical composition with lyrics"),
("rain", "Water falling from the sky"),
("tree", "Tall plant with a trunk"),
("dark", "Absence of light"),
("wind", "Moving air"),
("fall", "Season between summer and winter"),
("bear", "Large mammal with fur"),
("sexy", "Appealing and attractive"),
("yoda", "Wise, green Jedi Master"),
("meme", "Internet humor in the form of an image or video"),
("rock", "Music genre"),
("saga", "Epic narrative or series of events"),
("vlog", "Video blog on platforms like YouTube"),
("beta", "Passive and lowest in the pecking order"),
("exam", "Assessment of knowledge"),
("grad", "Type of school"),
("labs", "Walter White cooks here"),
("stud", "An absolute beauty"),
("dean", "Administrative head of a college"),
("text", "Required reading material"),
("math", "Study of numbers and quantities"),
("trip", "Journey or vacation"),
("tour", "Guided travel experience"),
("rest", "A type of software architecture commonly adopted by APIs"),
("stay", "Temporary residence during a trip"),
("sand", "Granular material on beaches"),
("view", "Scenic sight or landscape"),
("null", "Associated with the value of zero"),
("drop", "You don't want to do this to your baby"),
("golf", "Rich, old people love to do this"),
("snow", "Lots of this in the winter"),
("time", "____ is money"),
("rent", "Something we should raise for all single mothers"),
("bash", "A Unix shell");